/*
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BrowserAutomationDSLRuntimeModule extends AbstractBrowserAutomationDSLRuntimeModule {
}
