/*
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BrowserAutomationDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Model");
		private final Assignment cCommandsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cCommandsCommandParserRuleCall_0 = (RuleCall)cCommandsAssignment.eContents().get(0);
		
		//Model:
		//    commands+=Command*;
		@Override public ParserRule getRule() { return rule; }
		
		//commands+=Command*
		public Assignment getCommandsAssignment() { return cCommandsAssignment; }
		
		//Command
		public RuleCall getCommandsCommandParserRuleCall_0() { return cCommandsCommandParserRuleCall_0; }
	}
	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Command");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOpenBrowserParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGoToParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cClickParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFillParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cSelectParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cVerifyParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cReadParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cPasteParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cUncheckParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cComboboxParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		
		//Command:
		//    OpenBrowser | GoTo | Click | Fill | Select | Verify | Read | Paste | Uncheck | Combobox;
		@Override public ParserRule getRule() { return rule; }
		
		//OpenBrowser | GoTo | Click | Fill | Select | Verify | Read | Paste | Uncheck | Combobox
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OpenBrowser
		public RuleCall getOpenBrowserParserRuleCall_0() { return cOpenBrowserParserRuleCall_0; }
		
		//GoTo
		public RuleCall getGoToParserRuleCall_1() { return cGoToParserRuleCall_1; }
		
		//Click
		public RuleCall getClickParserRuleCall_2() { return cClickParserRuleCall_2; }
		
		//Fill
		public RuleCall getFillParserRuleCall_3() { return cFillParserRuleCall_3; }
		
		//Select
		public RuleCall getSelectParserRuleCall_4() { return cSelectParserRuleCall_4; }
		
		//Verify
		public RuleCall getVerifyParserRuleCall_5() { return cVerifyParserRuleCall_5; }
		
		//Read
		public RuleCall getReadParserRuleCall_6() { return cReadParserRuleCall_6; }
		
		//Paste
		public RuleCall getPasteParserRuleCall_7() { return cPasteParserRuleCall_7; }
		
		//Uncheck
		public RuleCall getUncheckParserRuleCall_8() { return cUncheckParserRuleCall_8; }
		
		//Combobox
		public RuleCall getComboboxParserRuleCall_9() { return cComboboxParserRuleCall_9; }
	}
	public class OpenBrowserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.OpenBrowser");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOpenBrowserAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOpenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cBrowserKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cWindowKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//OpenBrowser:
		//    {OpenBrowser} 'open' 'a' 'browser' 'window';
		@Override public ParserRule getRule() { return rule; }
		
		//{OpenBrowser} 'open' 'a' 'browser' 'window'
		public Group getGroup() { return cGroup; }
		
		//{OpenBrowser}
		public Action getOpenBrowserAction_0() { return cOpenBrowserAction_0; }
		
		//'open'
		public Keyword getOpenKeyword_1() { return cOpenKeyword_1; }
		
		//'a'
		public Keyword getAKeyword_2() { return cAKeyword_2; }
		
		//'browser'
		public Keyword getBrowserKeyword_3() { return cBrowserKeyword_3; }
		
		//'window'
		public Keyword getWindowKeyword_4() { return cWindowKeyword_4; }
	}
	public class GoToElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.GoTo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cToKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUrlKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUrlNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUrlNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cUrlNameAssignment_3.eContents().get(0);
		
		//GoTo:
		//    'go' 'to' 'url' urlName=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'go' 'to' 'url' urlName=STRING
		public Group getGroup() { return cGroup; }
		
		//'go'
		public Keyword getGoKeyword_0() { return cGoKeyword_0; }
		
		//'to'
		public Keyword getToKeyword_1() { return cToKeyword_1; }
		
		//'url'
		public Keyword getUrlKeyword_2() { return cUrlKeyword_2; }
		
		//urlName=STRING
		public Assignment getUrlNameAssignment_3() { return cUrlNameAssignment_3; }
		
		//STRING
		public RuleCall getUrlNameSTRINGTerminalRuleCall_3_0() { return cUrlNameSTRINGTerminalRuleCall_3_0; }
	}
	public class ClickElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Click");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClickAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cClickKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOnKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cTheKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Keyword cLinkKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Assignment cLinkTextAssignment_3_0_2 = (Assignment)cGroup_3_0.eContents().get(2);
		private final RuleCall cLinkTextSTRINGTerminalRuleCall_3_0_2_0 = (RuleCall)cLinkTextAssignment_3_0_2.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cTheKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Keyword cButtonKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Keyword cWithKeyword_3_1_2 = (Keyword)cGroup_3_1.eContents().get(2);
		private final Keyword cTextKeyword_3_1_3 = (Keyword)cGroup_3_1.eContents().get(3);
		private final Assignment cButtonTextAssignment_3_1_4 = (Assignment)cGroup_3_1.eContents().get(4);
		private final RuleCall cButtonTextSTRINGTerminalRuleCall_3_1_4_0 = (RuleCall)cButtonTextAssignment_3_1_4.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cAlternatives_3.eContents().get(2);
		private final Keyword cTheKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Keyword cImageKeyword_3_2_1 = (Keyword)cGroup_3_2.eContents().get(1);
		private final Keyword cWithKeyword_3_2_2 = (Keyword)cGroup_3_2.eContents().get(2);
		private final Keyword cAltKeyword_3_2_3 = (Keyword)cGroup_3_2.eContents().get(3);
		private final Keyword cPropertyKeyword_3_2_4 = (Keyword)cGroup_3_2.eContents().get(4);
		private final Assignment cAltAssignment_3_2_5 = (Assignment)cGroup_3_2.eContents().get(5);
		private final RuleCall cAltSTRINGTerminalRuleCall_3_2_5_0 = (RuleCall)cAltAssignment_3_2_5.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cAlternatives_3.eContents().get(3);
		private final Keyword cTheKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Keyword cUrlKeyword_3_3_1 = (Keyword)cGroup_3_3.eContents().get(1);
		
		//Click:
		//    {Click} 'click' 'on' ('the' 'link' linkText=STRING | 'the' 'button' 'with' 'text' buttonText=STRING | 'the' 'image' 'with' 'alt' 'property' alt=STRING | 'the' 'url');
		@Override public ParserRule getRule() { return rule; }
		
		//{Click} 'click' 'on' ('the' 'link' linkText=STRING | 'the' 'button' 'with' 'text' buttonText=STRING | 'the' 'image' 'with' 'alt' 'property' alt=STRING | 'the' 'url')
		public Group getGroup() { return cGroup; }
		
		//{Click}
		public Action getClickAction_0() { return cClickAction_0; }
		
		//'click'
		public Keyword getClickKeyword_1() { return cClickKeyword_1; }
		
		//'on'
		public Keyword getOnKeyword_2() { return cOnKeyword_2; }
		
		//('the' 'link' linkText=STRING | 'the' 'button' 'with' 'text' buttonText=STRING | 'the' 'image' 'with' 'alt' 'property' alt=STRING | 'the' 'url')
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'the' 'link' linkText=STRING
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'the'
		public Keyword getTheKeyword_3_0_0() { return cTheKeyword_3_0_0; }
		
		//'link'
		public Keyword getLinkKeyword_3_0_1() { return cLinkKeyword_3_0_1; }
		
		//linkText=STRING
		public Assignment getLinkTextAssignment_3_0_2() { return cLinkTextAssignment_3_0_2; }
		
		//STRING
		public RuleCall getLinkTextSTRINGTerminalRuleCall_3_0_2_0() { return cLinkTextSTRINGTerminalRuleCall_3_0_2_0; }
		
		//'the' 'button' 'with' 'text' buttonText=STRING
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'the'
		public Keyword getTheKeyword_3_1_0() { return cTheKeyword_3_1_0; }
		
		//'button'
		public Keyword getButtonKeyword_3_1_1() { return cButtonKeyword_3_1_1; }
		
		//'with'
		public Keyword getWithKeyword_3_1_2() { return cWithKeyword_3_1_2; }
		
		//'text'
		public Keyword getTextKeyword_3_1_3() { return cTextKeyword_3_1_3; }
		
		//buttonText=STRING
		public Assignment getButtonTextAssignment_3_1_4() { return cButtonTextAssignment_3_1_4; }
		
		//STRING
		public RuleCall getButtonTextSTRINGTerminalRuleCall_3_1_4_0() { return cButtonTextSTRINGTerminalRuleCall_3_1_4_0; }
		
		//'the' 'image' 'with' 'alt' 'property' alt=STRING
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//'the'
		public Keyword getTheKeyword_3_2_0() { return cTheKeyword_3_2_0; }
		
		//'image'
		public Keyword getImageKeyword_3_2_1() { return cImageKeyword_3_2_1; }
		
		//'with'
		public Keyword getWithKeyword_3_2_2() { return cWithKeyword_3_2_2; }
		
		//'alt'
		public Keyword getAltKeyword_3_2_3() { return cAltKeyword_3_2_3; }
		
		//'property'
		public Keyword getPropertyKeyword_3_2_4() { return cPropertyKeyword_3_2_4; }
		
		//alt=STRING
		public Assignment getAltAssignment_3_2_5() { return cAltAssignment_3_2_5; }
		
		//STRING
		public RuleCall getAltSTRINGTerminalRuleCall_3_2_5_0() { return cAltSTRINGTerminalRuleCall_3_2_5_0; }
		
		//'the' 'url'
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//'the'
		public Keyword getTheKeyword_3_3_0() { return cTheKeyword_3_3_0; }
		
		//'url'
		public Keyword getUrlKeyword_3_3_1() { return cUrlKeyword_3_3_1; }
	}
	public class FillElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Fill");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFillKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTheKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cTextKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Keyword cFieldKeyword_2_0_1 = (Keyword)cGroup_2_0.eContents().get(1);
		private final Assignment cFieldNameAssignment_2_0_2 = (Assignment)cGroup_2_0.eContents().get(2);
		private final RuleCall cFieldNameSTRINGTerminalRuleCall_2_0_2_0 = (RuleCall)cFieldNameAssignment_2_0_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cSearchKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cFieldKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Keyword cWithKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTextToFillAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTextToFillSTRINGTerminalRuleCall_4_0 = (RuleCall)cTextToFillAssignment_4.eContents().get(0);
		
		//Fill:
		//    'fill' 'the' ('text' 'field' fieldName=STRING | 'search' 'field') 'with' textToFill=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'fill' 'the' ('text' 'field' fieldName=STRING | 'search' 'field') 'with' textToFill=STRING
		public Group getGroup() { return cGroup; }
		
		//'fill'
		public Keyword getFillKeyword_0() { return cFillKeyword_0; }
		
		//'the'
		public Keyword getTheKeyword_1() { return cTheKeyword_1; }
		
		//('text' 'field' fieldName=STRING | 'search' 'field')
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//'text' 'field' fieldName=STRING
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'text'
		public Keyword getTextKeyword_2_0_0() { return cTextKeyword_2_0_0; }
		
		//'field'
		public Keyword getFieldKeyword_2_0_1() { return cFieldKeyword_2_0_1; }
		
		//fieldName=STRING
		public Assignment getFieldNameAssignment_2_0_2() { return cFieldNameAssignment_2_0_2; }
		
		//STRING
		public RuleCall getFieldNameSTRINGTerminalRuleCall_2_0_2_0() { return cFieldNameSTRINGTerminalRuleCall_2_0_2_0; }
		
		//'search' 'field'
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'search'
		public Keyword getSearchKeyword_2_1_0() { return cSearchKeyword_2_1_0; }
		
		//'field'
		public Keyword getFieldKeyword_2_1_1() { return cFieldKeyword_2_1_1; }
		
		//'with'
		public Keyword getWithKeyword_3() { return cWithKeyword_3; }
		
		//textToFill=STRING
		public Assignment getTextToFillAssignment_4() { return cTextToFillAssignment_4; }
		
		//STRING
		public RuleCall getTextToFillSTRINGTerminalRuleCall_4_0() { return cTextToFillSTRINGTerminalRuleCall_4_0; }
	}
	public class SelectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Select");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTheKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCheckboxKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cNamedKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Assignment cCheckboxNameAssignment_3_0_1 = (Assignment)cGroup_3_0.eContents().get(1);
		private final RuleCall cCheckboxNameSTRINGTerminalRuleCall_3_0_1_0 = (RuleCall)cCheckboxNameAssignment_3_0_1.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cWithKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Keyword cValuesKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Assignment cValuesAssignment_3_1_2 = (Assignment)cGroup_3_1.eContents().get(2);
		private final RuleCall cValuesSTRINGTerminalRuleCall_3_1_2_0 = (RuleCall)cValuesAssignment_3_1_2.eContents().get(0);
		private final Group cGroup_3_1_3 = (Group)cGroup_3_1.eContents().get(3);
		private final Keyword cCommaKeyword_3_1_3_0 = (Keyword)cGroup_3_1_3.eContents().get(0);
		private final Assignment cValuesAssignment_3_1_3_1 = (Assignment)cGroup_3_1_3.eContents().get(1);
		private final RuleCall cValuesSTRINGTerminalRuleCall_3_1_3_1_0 = (RuleCall)cValuesAssignment_3_1_3_1.eContents().get(0);
		
		//Select:
		//    'select' 'the' 'checkbox' ('named' checkboxName=STRING | 'with' 'values' values+=STRING (',' values+=STRING)*);
		@Override public ParserRule getRule() { return rule; }
		
		//'select' 'the' 'checkbox' ('named' checkboxName=STRING | 'with' 'values' values+=STRING (',' values+=STRING)*)
		public Group getGroup() { return cGroup; }
		
		//'select'
		public Keyword getSelectKeyword_0() { return cSelectKeyword_0; }
		
		//'the'
		public Keyword getTheKeyword_1() { return cTheKeyword_1; }
		
		//'checkbox'
		public Keyword getCheckboxKeyword_2() { return cCheckboxKeyword_2; }
		
		//('named' checkboxName=STRING | 'with' 'values' values+=STRING (',' values+=STRING)*)
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'named' checkboxName=STRING
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'named'
		public Keyword getNamedKeyword_3_0_0() { return cNamedKeyword_3_0_0; }
		
		//checkboxName=STRING
		public Assignment getCheckboxNameAssignment_3_0_1() { return cCheckboxNameAssignment_3_0_1; }
		
		//STRING
		public RuleCall getCheckboxNameSTRINGTerminalRuleCall_3_0_1_0() { return cCheckboxNameSTRINGTerminalRuleCall_3_0_1_0; }
		
		//'with' 'values' values+=STRING (',' values+=STRING)*
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'with'
		public Keyword getWithKeyword_3_1_0() { return cWithKeyword_3_1_0; }
		
		//'values'
		public Keyword getValuesKeyword_3_1_1() { return cValuesKeyword_3_1_1; }
		
		//values+=STRING
		public Assignment getValuesAssignment_3_1_2() { return cValuesAssignment_3_1_2; }
		
		//STRING
		public RuleCall getValuesSTRINGTerminalRuleCall_3_1_2_0() { return cValuesSTRINGTerminalRuleCall_3_1_2_0; }
		
		//(',' values+=STRING)*
		public Group getGroup_3_1_3() { return cGroup_3_1_3; }
		
		//','
		public Keyword getCommaKeyword_3_1_3_0() { return cCommaKeyword_3_1_3_0; }
		
		//values+=STRING
		public Assignment getValuesAssignment_3_1_3_1() { return cValuesAssignment_3_1_3_1; }
		
		//STRING
		public RuleCall getValuesSTRINGTerminalRuleCall_3_1_3_1_0() { return cValuesSTRINGTerminalRuleCall_3_1_3_1_0; }
	}
	public class VerifyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Verify");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVerifyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVerifyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cThatKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTheKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cPageKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cContainsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final Group cGroup_6_0 = (Group)cAlternatives_6.eContents().get(0);
		private final Keyword cAKeyword_6_0_0 = (Keyword)cGroup_6_0.eContents().get(0);
		private final Keyword cTitleKeyword_6_0_1 = (Keyword)cGroup_6_0.eContents().get(1);
		private final Keyword cOfKeyword_6_0_2 = (Keyword)cGroup_6_0.eContents().get(2);
		private final Keyword cTheKeyword_6_0_3 = (Keyword)cGroup_6_0.eContents().get(3);
		private final Keyword cPreviouslyKeyword_6_0_4 = (Keyword)cGroup_6_0.eContents().get(4);
		private final Keyword cClickedKeyword_6_0_5 = (Keyword)cGroup_6_0.eContents().get(5);
		private final Keyword cNewsKeyword_6_0_6 = (Keyword)cGroup_6_0.eContents().get(6);
		private final Group cGroup_6_1 = (Group)cAlternatives_6.eContents().get(1);
		private final Keyword cTheKeyword_6_1_0 = (Keyword)cGroup_6_1.eContents().get(0);
		private final Keyword cStringKeyword_6_1_1 = (Keyword)cGroup_6_1.eContents().get(1);
		private final Assignment cTextToVerifyAssignment_6_1_2 = (Assignment)cGroup_6_1.eContents().get(2);
		private final RuleCall cTextToVerifySTRINGTerminalRuleCall_6_1_2_0 = (RuleCall)cTextToVerifyAssignment_6_1_2.eContents().get(0);
		private final Group cGroup_6_2 = (Group)cAlternatives_6.eContents().get(2);
		private final Keyword cAKeyword_6_2_0 = (Keyword)cGroup_6_2.eContents().get(0);
		private final Keyword cLinkKeyword_6_2_1 = (Keyword)cGroup_6_2.eContents().get(1);
		private final Assignment cLinkToVerifyAssignment_6_2_2 = (Assignment)cGroup_6_2.eContents().get(2);
		private final RuleCall cLinkToVerifySTRINGTerminalRuleCall_6_2_2_0 = (RuleCall)cLinkToVerifyAssignment_6_2_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cAlternatives_6.eContents().get(3);
		private final Keyword cAKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Keyword cLinkKeyword_6_3_1 = (Keyword)cGroup_6_3.eContents().get(1);
		private final Keyword cToKeyword_6_3_2 = (Keyword)cGroup_6_3.eContents().get(2);
		private final Keyword cTheKeyword_6_3_3 = (Keyword)cGroup_6_3.eContents().get(3);
		private final Keyword cPreviousKeyword_6_3_4 = (Keyword)cGroup_6_3.eContents().get(4);
		private final Keyword cUrlKeyword_6_3_5 = (Keyword)cGroup_6_3.eContents().get(5);
		
		//Verify:
		//    {Verify} 'verify' 'that' 'the' 'page' 'contains' ('a' 'title' 'of' 'the' 'previously' 'clicked' 'news' | 'the' 'string' textToVerify=STRING | 'a' 'link' linkToVerify=STRING | 'a' 'link' 'to' 'the' 'previous' 'url');
		@Override public ParserRule getRule() { return rule; }
		
		//{Verify} 'verify' 'that' 'the' 'page' 'contains' ('a' 'title' 'of' 'the' 'previously' 'clicked' 'news' | 'the' 'string' textToVerify=STRING | 'a' 'link' linkToVerify=STRING | 'a' 'link' 'to' 'the' 'previous' 'url')
		public Group getGroup() { return cGroup; }
		
		//{Verify}
		public Action getVerifyAction_0() { return cVerifyAction_0; }
		
		//'verify'
		public Keyword getVerifyKeyword_1() { return cVerifyKeyword_1; }
		
		//'that'
		public Keyword getThatKeyword_2() { return cThatKeyword_2; }
		
		//'the'
		public Keyword getTheKeyword_3() { return cTheKeyword_3; }
		
		//'page'
		public Keyword getPageKeyword_4() { return cPageKeyword_4; }
		
		//'contains'
		public Keyword getContainsKeyword_5() { return cContainsKeyword_5; }
		
		//('a' 'title' 'of' 'the' 'previously' 'clicked' 'news' | 'the' 'string' textToVerify=STRING | 'a' 'link' linkToVerify=STRING | 'a' 'link' 'to' 'the' 'previous' 'url')
		public Alternatives getAlternatives_6() { return cAlternatives_6; }
		
		//'a' 'title' 'of' 'the' 'previously' 'clicked' 'news'
		public Group getGroup_6_0() { return cGroup_6_0; }
		
		//'a'
		public Keyword getAKeyword_6_0_0() { return cAKeyword_6_0_0; }
		
		//'title'
		public Keyword getTitleKeyword_6_0_1() { return cTitleKeyword_6_0_1; }
		
		//'of'
		public Keyword getOfKeyword_6_0_2() { return cOfKeyword_6_0_2; }
		
		//'the'
		public Keyword getTheKeyword_6_0_3() { return cTheKeyword_6_0_3; }
		
		//'previously'
		public Keyword getPreviouslyKeyword_6_0_4() { return cPreviouslyKeyword_6_0_4; }
		
		//'clicked'
		public Keyword getClickedKeyword_6_0_5() { return cClickedKeyword_6_0_5; }
		
		//'news'
		public Keyword getNewsKeyword_6_0_6() { return cNewsKeyword_6_0_6; }
		
		//'the' 'string' textToVerify=STRING
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//'the'
		public Keyword getTheKeyword_6_1_0() { return cTheKeyword_6_1_0; }
		
		//'string'
		public Keyword getStringKeyword_6_1_1() { return cStringKeyword_6_1_1; }
		
		//textToVerify=STRING
		public Assignment getTextToVerifyAssignment_6_1_2() { return cTextToVerifyAssignment_6_1_2; }
		
		//STRING
		public RuleCall getTextToVerifySTRINGTerminalRuleCall_6_1_2_0() { return cTextToVerifySTRINGTerminalRuleCall_6_1_2_0; }
		
		//'a' 'link' linkToVerify=STRING
		public Group getGroup_6_2() { return cGroup_6_2; }
		
		//'a'
		public Keyword getAKeyword_6_2_0() { return cAKeyword_6_2_0; }
		
		//'link'
		public Keyword getLinkKeyword_6_2_1() { return cLinkKeyword_6_2_1; }
		
		//linkToVerify=STRING
		public Assignment getLinkToVerifyAssignment_6_2_2() { return cLinkToVerifyAssignment_6_2_2; }
		
		//STRING
		public RuleCall getLinkToVerifySTRINGTerminalRuleCall_6_2_2_0() { return cLinkToVerifySTRINGTerminalRuleCall_6_2_2_0; }
		
		//'a' 'link' 'to' 'the' 'previous' 'url'
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//'a'
		public Keyword getAKeyword_6_3_0() { return cAKeyword_6_3_0; }
		
		//'link'
		public Keyword getLinkKeyword_6_3_1() { return cLinkKeyword_6_3_1; }
		
		//'to'
		public Keyword getToKeyword_6_3_2() { return cToKeyword_6_3_2; }
		
		//'the'
		public Keyword getTheKeyword_6_3_3() { return cTheKeyword_6_3_3; }
		
		//'previous'
		public Keyword getPreviousKeyword_6_3_4() { return cPreviousKeyword_6_3_4; }
		
		//'url'
		public Keyword getUrlKeyword_6_3_5() { return cUrlKeyword_6_3_5; }
	}
	public class ReadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Read");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReadKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTheKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTitleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cAndKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cUrlKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cOfKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cTheKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cNewsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cNumberKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cNumberAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cNumberINTTerminalRuleCall_9_0 = (RuleCall)cNumberAssignment_9.eContents().get(0);
		private final Keyword cInKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cTheKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cPageKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Read:
		//    'read' 'the' 'title' 'and' 'url' 'of' 'the' 'news' 'number' number=INT 'in' 'the' 'page';
		@Override public ParserRule getRule() { return rule; }
		
		//'read' 'the' 'title' 'and' 'url' 'of' 'the' 'news' 'number' number=INT 'in' 'the' 'page'
		public Group getGroup() { return cGroup; }
		
		//'read'
		public Keyword getReadKeyword_0() { return cReadKeyword_0; }
		
		//'the'
		public Keyword getTheKeyword_1() { return cTheKeyword_1; }
		
		//'title'
		public Keyword getTitleKeyword_2() { return cTitleKeyword_2; }
		
		//'and'
		public Keyword getAndKeyword_3() { return cAndKeyword_3; }
		
		//'url'
		public Keyword getUrlKeyword_4() { return cUrlKeyword_4; }
		
		//'of'
		public Keyword getOfKeyword_5() { return cOfKeyword_5; }
		
		//'the'
		public Keyword getTheKeyword_6() { return cTheKeyword_6; }
		
		//'news'
		public Keyword getNewsKeyword_7() { return cNewsKeyword_7; }
		
		//'number'
		public Keyword getNumberKeyword_8() { return cNumberKeyword_8; }
		
		//number=INT
		public Assignment getNumberAssignment_9() { return cNumberAssignment_9; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_9_0() { return cNumberINTTerminalRuleCall_9_0; }
		
		//'in'
		public Keyword getInKeyword_10() { return cInKeyword_10; }
		
		//'the'
		public Keyword getTheKeyword_11() { return cTheKeyword_11; }
		
		//'page'
		public Keyword getPageKeyword_12() { return cPageKeyword_12; }
	}
	public class PasteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Paste");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPasteAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPasteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTheKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTitleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cInKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Group cGroup_5_0 = (Group)cAlternatives_5.eContents().get(0);
		private final Keyword cTheKeyword_5_0_0 = (Keyword)cGroup_5_0.eContents().get(0);
		private final Keyword cSearchKeyword_5_0_1 = (Keyword)cGroup_5_0.eContents().get(1);
		private final Keyword cFieldKeyword_5_0_2 = (Keyword)cGroup_5_0.eContents().get(2);
		private final Group cGroup_5_1 = (Group)cAlternatives_5.eContents().get(1);
		private final Keyword cSearchKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Keyword cFieldKeyword_5_1_1 = (Keyword)cGroup_5_1.eContents().get(1);
		
		//Paste:
		//    {Paste} 'paste' 'the' 'title' 'in' ('the' 'search' 'field' | 'search' 'field');
		@Override public ParserRule getRule() { return rule; }
		
		//{Paste} 'paste' 'the' 'title' 'in' ('the' 'search' 'field' | 'search' 'field')
		public Group getGroup() { return cGroup; }
		
		//{Paste}
		public Action getPasteAction_0() { return cPasteAction_0; }
		
		//'paste'
		public Keyword getPasteKeyword_1() { return cPasteKeyword_1; }
		
		//'the'
		public Keyword getTheKeyword_2() { return cTheKeyword_2; }
		
		//'title'
		public Keyword getTitleKeyword_3() { return cTitleKeyword_3; }
		
		//'in'
		public Keyword getInKeyword_4() { return cInKeyword_4; }
		
		//('the' 'search' 'field' | 'search' 'field')
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//'the' 'search' 'field'
		public Group getGroup_5_0() { return cGroup_5_0; }
		
		//'the'
		public Keyword getTheKeyword_5_0_0() { return cTheKeyword_5_0_0; }
		
		//'search'
		public Keyword getSearchKeyword_5_0_1() { return cSearchKeyword_5_0_1; }
		
		//'field'
		public Keyword getFieldKeyword_5_0_2() { return cFieldKeyword_5_0_2; }
		
		//'search' 'field'
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//'search'
		public Keyword getSearchKeyword_5_1_0() { return cSearchKeyword_5_1_0; }
		
		//'field'
		public Keyword getFieldKeyword_5_1_1() { return cFieldKeyword_5_1_1; }
	}
	public class UncheckElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Uncheck");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUncheckAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUncheckKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAllKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCheckboxesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Uncheck:
		//    {Uncheck} 'uncheck' 'all' 'checkboxes';
		@Override public ParserRule getRule() { return rule; }
		
		//{Uncheck} 'uncheck' 'all' 'checkboxes'
		public Group getGroup() { return cGroup; }
		
		//{Uncheck}
		public Action getUncheckAction_0() { return cUncheckAction_0; }
		
		//'uncheck'
		public Keyword getUncheckKeyword_1() { return cUncheckKeyword_1; }
		
		//'all'
		public Keyword getAllKeyword_2() { return cAllKeyword_2; }
		
		//'checkboxes'
		public Keyword getCheckboxesKeyword_3() { return cCheckboxesKeyword_3; }
	}
	public class ComboboxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL.Combobox");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChooseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTheKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOptionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOptionSTRINGTerminalRuleCall_3_0 = (RuleCall)cOptionAssignment_3.eContents().get(0);
		private final Keyword cInKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cTheKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cComboboxKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cLabelAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLabelSTRINGTerminalRuleCall_7_0 = (RuleCall)cLabelAssignment_7.eContents().get(0);
		
		//Combobox:
		//    'choose' 'the' 'option' option=STRING 'in' 'the' 'combobox' label=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'choose' 'the' 'option' option=STRING 'in' 'the' 'combobox' label=STRING
		public Group getGroup() { return cGroup; }
		
		//'choose'
		public Keyword getChooseKeyword_0() { return cChooseKeyword_0; }
		
		//'the'
		public Keyword getTheKeyword_1() { return cTheKeyword_1; }
		
		//'option'
		public Keyword getOptionKeyword_2() { return cOptionKeyword_2; }
		
		//option=STRING
		public Assignment getOptionAssignment_3() { return cOptionAssignment_3; }
		
		//STRING
		public RuleCall getOptionSTRINGTerminalRuleCall_3_0() { return cOptionSTRINGTerminalRuleCall_3_0; }
		
		//'in'
		public Keyword getInKeyword_4() { return cInKeyword_4; }
		
		//'the'
		public Keyword getTheKeyword_5() { return cTheKeyword_5; }
		
		//'combobox'
		public Keyword getComboboxKeyword_6() { return cComboboxKeyword_6; }
		
		//label=STRING
		public Assignment getLabelAssignment_7() { return cLabelAssignment_7; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_7_0() { return cLabelSTRINGTerminalRuleCall_7_0; }
	}
	
	
	private final ModelElements pModel;
	private final CommandElements pCommand;
	private final OpenBrowserElements pOpenBrowser;
	private final GoToElements pGoTo;
	private final ClickElements pClick;
	private final FillElements pFill;
	private final SelectElements pSelect;
	private final VerifyElements pVerify;
	private final ReadElements pRead;
	private final PasteElements pPaste;
	private final UncheckElements pUncheck;
	private final ComboboxElements pCombobox;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BrowserAutomationDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pCommand = new CommandElements();
		this.pOpenBrowser = new OpenBrowserElements();
		this.pGoTo = new GoToElements();
		this.pClick = new ClickElements();
		this.pFill = new FillElements();
		this.pSelect = new SelectElements();
		this.pVerify = new VerifyElements();
		this.pRead = new ReadElements();
		this.pPaste = new PasteElements();
		this.pUncheck = new UncheckElements();
		this.pCombobox = new ComboboxElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.imta.yperiquoi.browserautomation.BrowserAutomationDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    commands+=Command*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Command:
	//    OpenBrowser | GoTo | Click | Fill | Select | Verify | Read | Paste | Uncheck | Combobox;
	public CommandElements getCommandAccess() {
		return pCommand;
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}
	
	//OpenBrowser:
	//    {OpenBrowser} 'open' 'a' 'browser' 'window';
	public OpenBrowserElements getOpenBrowserAccess() {
		return pOpenBrowser;
	}
	
	public ParserRule getOpenBrowserRule() {
		return getOpenBrowserAccess().getRule();
	}
	
	//GoTo:
	//    'go' 'to' 'url' urlName=STRING;
	public GoToElements getGoToAccess() {
		return pGoTo;
	}
	
	public ParserRule getGoToRule() {
		return getGoToAccess().getRule();
	}
	
	//Click:
	//    {Click} 'click' 'on' ('the' 'link' linkText=STRING | 'the' 'button' 'with' 'text' buttonText=STRING | 'the' 'image' 'with' 'alt' 'property' alt=STRING | 'the' 'url');
	public ClickElements getClickAccess() {
		return pClick;
	}
	
	public ParserRule getClickRule() {
		return getClickAccess().getRule();
	}
	
	//Fill:
	//    'fill' 'the' ('text' 'field' fieldName=STRING | 'search' 'field') 'with' textToFill=STRING;
	public FillElements getFillAccess() {
		return pFill;
	}
	
	public ParserRule getFillRule() {
		return getFillAccess().getRule();
	}
	
	//Select:
	//    'select' 'the' 'checkbox' ('named' checkboxName=STRING | 'with' 'values' values+=STRING (',' values+=STRING)*);
	public SelectElements getSelectAccess() {
		return pSelect;
	}
	
	public ParserRule getSelectRule() {
		return getSelectAccess().getRule();
	}
	
	//Verify:
	//    {Verify} 'verify' 'that' 'the' 'page' 'contains' ('a' 'title' 'of' 'the' 'previously' 'clicked' 'news' | 'the' 'string' textToVerify=STRING | 'a' 'link' linkToVerify=STRING | 'a' 'link' 'to' 'the' 'previous' 'url');
	public VerifyElements getVerifyAccess() {
		return pVerify;
	}
	
	public ParserRule getVerifyRule() {
		return getVerifyAccess().getRule();
	}
	
	//Read:
	//    'read' 'the' 'title' 'and' 'url' 'of' 'the' 'news' 'number' number=INT 'in' 'the' 'page';
	public ReadElements getReadAccess() {
		return pRead;
	}
	
	public ParserRule getReadRule() {
		return getReadAccess().getRule();
	}
	
	//Paste:
	//    {Paste} 'paste' 'the' 'title' 'in' ('the' 'search' 'field' | 'search' 'field');
	public PasteElements getPasteAccess() {
		return pPaste;
	}
	
	public ParserRule getPasteRule() {
		return getPasteAccess().getRule();
	}
	
	//Uncheck:
	//    {Uncheck} 'uncheck' 'all' 'checkboxes';
	public UncheckElements getUncheckAccess() {
		return pUncheck;
	}
	
	public ParserRule getUncheckRule() {
		return getUncheckAccess().getRule();
	}
	
	//Combobox:
	//    'choose' 'the' 'option' option=STRING 'in' 'the' 'combobox' label=STRING;
	public ComboboxElements getComboboxAccess() {
		return pCombobox;
	}
	
	public ParserRule getComboboxRule() {
		return getComboboxAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
