/*
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class BrowserAutomationDSLScopeProvider extends AbstractBrowserAutomationDSLScopeProvider {

}
