/**
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.browserAutomationDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLFactory
 * @model kind="package"
 * @generated
 */
public interface BrowserAutomationDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "browserAutomationDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imta.fr/yperiquoi/browserautomation/BrowserAutomationDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "browserAutomationDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserAutomationDSLPackage eINSTANCE = fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ModelImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.CommandImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.OpenBrowserImpl <em>Open Browser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.OpenBrowserImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getOpenBrowser()
   * @generated
   */
  int OPEN_BROWSER = 2;

  /**
   * The number of structural features of the '<em>Open Browser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_BROWSER_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.GoToImpl <em>Go To</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.GoToImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getGoTo()
   * @generated
   */
  int GO_TO = 3;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO__URL = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go To</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ClickImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getClick()
   * @generated
   */
  int CLICK = 4;

  /**
   * The feature id for the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__LINK_TEXT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Button Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__BUTTON_TEXT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Alt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__ALT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__VARIABLE = COMMAND_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.FillImpl <em>Fill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.FillImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getFill()
   * @generated
   */
  int FILL = 5;

  /**
   * The feature id for the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__FIELD_NAME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Text To Fill</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__TEXT_TO_FILL = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__VARIABLE = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Fill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.SelectImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 6;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__VALUES = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.VerifyImpl <em>Verify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.VerifyImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getVerify()
   * @generated
   */
  int VERIFY = 7;

  /**
   * The feature id for the '<em><b>Text To Verify</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__TEXT_TO_VERIFY = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Link To Verify</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__LINK_TO_VERIFY = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__VARIABLE = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Verify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ReadImpl <em>Read</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ReadImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getRead()
   * @generated
   */
  int READ = 8;

  /**
   * The feature id for the '<em><b>Elements</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__ELEMENTS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__LINK_TEXT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__NUMBER = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Read</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.UncheckImpl <em>Uncheck</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.UncheckImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getUncheck()
   * @generated
   */
  int UNCHECK = 9;

  /**
   * The number of structural features of the '<em>Uncheck</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCHECK_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ComboboxImpl <em>Combobox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ComboboxImpl
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getCombobox()
   * @generated
   */
  int COMBOBOX = 10;

  /**
   * The feature id for the '<em><b>Option</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__OPTION = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX__LABEL = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Combobox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMBOBOX_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Model#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Model#getCommands()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Commands();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.OpenBrowser <em>Open Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open Browser</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.OpenBrowser
   * @generated
   */
  EClass getOpenBrowser();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.GoTo <em>Go To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go To</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.GoTo
   * @generated
   */
  EClass getGoTo();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.GoTo#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.GoTo#getUrl()
   * @see #getGoTo()
   * @generated
   */
  EAttribute getGoTo_Url();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getLinkText <em>Link Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link Text</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getLinkText()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_LinkText();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getButtonText <em>Button Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Button Text</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getButtonText()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_ButtonText();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getAlt <em>Alt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alt</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getAlt()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_Alt();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getVariable()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_Variable();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Fill <em>Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Fill
   * @generated
   */
  EClass getFill();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Fill#getFieldName <em>Field Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Name</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Fill#getFieldName()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_FieldName();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Fill#getTextToFill <em>Text To Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text To Fill</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Fill#getTextToFill()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_TextToFill();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Fill#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Fill#getVariable()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_Variable();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the attribute list '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Select#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Select#getValues()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_Values();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify
   * @generated
   */
  EClass getVerify();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getTextToVerify <em>Text To Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text To Verify</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getTextToVerify()
   * @see #getVerify()
   * @generated
   */
  EAttribute getVerify_TextToVerify();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getLinkToVerify <em>Link To Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link To Verify</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getLinkToVerify()
   * @see #getVerify()
   * @generated
   */
  EAttribute getVerify_LinkToVerify();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getVariable()
   * @see #getVerify()
   * @generated
   */
  EAttribute getVerify_Variable();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Read <em>Read</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Read
   * @generated
   */
  EClass getRead();

  /**
   * Returns the meta object for the attribute list '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Read#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Elements</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Read#getElements()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_Elements();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Read#getLinkText <em>Link Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link Text</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Read#getLinkText()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_LinkText();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Read#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Read#getNumber()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_Number();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Uncheck <em>Uncheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uncheck</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Uncheck
   * @generated
   */
  EClass getUncheck();

  /**
   * Returns the meta object for class '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Combobox <em>Combobox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Combobox</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Combobox
   * @generated
   */
  EClass getCombobox();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Combobox#getOption <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Option</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Combobox#getOption()
   * @see #getCombobox()
   * @generated
   */
  EAttribute getCombobox_Option();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Combobox#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Combobox#getLabel()
   * @see #getCombobox()
   * @generated
   */
  EAttribute getCombobox_Label();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BrowserAutomationDSLFactory getBrowserAutomationDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ModelImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMMANDS = eINSTANCE.getModel_Commands();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.CommandImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.OpenBrowserImpl <em>Open Browser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.OpenBrowserImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getOpenBrowser()
     * @generated
     */
    EClass OPEN_BROWSER = eINSTANCE.getOpenBrowser();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.GoToImpl <em>Go To</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.GoToImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getGoTo()
     * @generated
     */
    EClass GO_TO = eINSTANCE.getGoTo();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO_TO__URL = eINSTANCE.getGoTo_Url();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ClickImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Link Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__LINK_TEXT = eINSTANCE.getClick_LinkText();

    /**
     * The meta object literal for the '<em><b>Button Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__BUTTON_TEXT = eINSTANCE.getClick_ButtonText();

    /**
     * The meta object literal for the '<em><b>Alt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__ALT = eINSTANCE.getClick_Alt();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__VARIABLE = eINSTANCE.getClick_Variable();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.FillImpl <em>Fill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.FillImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getFill()
     * @generated
     */
    EClass FILL = eINSTANCE.getFill();

    /**
     * The meta object literal for the '<em><b>Field Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__FIELD_NAME = eINSTANCE.getFill_FieldName();

    /**
     * The meta object literal for the '<em><b>Text To Fill</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__TEXT_TO_FILL = eINSTANCE.getFill_TextToFill();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__VARIABLE = eINSTANCE.getFill_Variable();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.SelectImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__VALUES = eINSTANCE.getSelect_Values();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.VerifyImpl <em>Verify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.VerifyImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getVerify()
     * @generated
     */
    EClass VERIFY = eINSTANCE.getVerify();

    /**
     * The meta object literal for the '<em><b>Text To Verify</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY__TEXT_TO_VERIFY = eINSTANCE.getVerify_TextToVerify();

    /**
     * The meta object literal for the '<em><b>Link To Verify</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY__LINK_TO_VERIFY = eINSTANCE.getVerify_LinkToVerify();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY__VARIABLE = eINSTANCE.getVerify_Variable();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ReadImpl <em>Read</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ReadImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getRead()
     * @generated
     */
    EClass READ = eINSTANCE.getRead();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__ELEMENTS = eINSTANCE.getRead_Elements();

    /**
     * The meta object literal for the '<em><b>Link Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__LINK_TEXT = eINSTANCE.getRead_LinkText();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__NUMBER = eINSTANCE.getRead_Number();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.UncheckImpl <em>Uncheck</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.UncheckImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getUncheck()
     * @generated
     */
    EClass UNCHECK = eINSTANCE.getUncheck();

    /**
     * The meta object literal for the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ComboboxImpl <em>Combobox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.ComboboxImpl
     * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.impl.BrowserAutomationDSLPackageImpl#getCombobox()
     * @generated
     */
    EClass COMBOBOX = eINSTANCE.getCombobox();

    /**
     * The meta object literal for the '<em><b>Option</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMBOBOX__OPTION = eINSTANCE.getCombobox_Option();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMBOBOX__LABEL = eINSTANCE.getCombobox_Label();

  }

} //BrowserAutomationDSLPackage
