/**
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.browserAutomationDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getLinkText <em>Link Text</em>}</li>
 *   <li>{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getButtonText <em>Button Text</em>}</li>
 *   <li>{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getAlt <em>Alt</em>}</li>
 * </ul>
 *
 * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getClick()
 * @model
 * @generated
 */
public interface Click extends Command
{
  /**
   * Returns the value of the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link Text</em>' attribute.
   * @see #setLinkText(String)
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getClick_LinkText()
   * @model
   * @generated
   */
  String getLinkText();

  /**
   * Sets the value of the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getLinkText <em>Link Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link Text</em>' attribute.
   * @see #getLinkText()
   * @generated
   */
  void setLinkText(String value);

  /**
   * Returns the value of the '<em><b>Button Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Button Text</em>' attribute.
   * @see #setButtonText(String)
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getClick_ButtonText()
   * @model
   * @generated
   */
  String getButtonText();

  /**
   * Sets the value of the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getButtonText <em>Button Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Button Text</em>' attribute.
   * @see #getButtonText()
   * @generated
   */
  void setButtonText(String value);

  /**
   * Returns the value of the '<em><b>Alt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' attribute.
   * @see #setAlt(String)
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getClick_Alt()
   * @model
   * @generated
   */
  String getAlt();

  /**
   * Sets the value of the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Click#getAlt <em>Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt</em>' attribute.
   * @see #getAlt()
   * @generated
   */
  void setAlt(String value);

} // Click
