/**
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.browserAutomationDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paste</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getPaste()
 * @model
 * @generated
 */
public interface Paste extends Command
{
} // Paste
