/**
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.browserAutomationDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Select#getCheckboxName <em>Checkbox Name</em>}</li>
 *   <li>{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Select#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getSelect()
 * @model
 * @generated
 */
public interface Select extends Command
{
  /**
   * Returns the value of the '<em><b>Checkbox Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Checkbox Name</em>' attribute.
   * @see #setCheckboxName(String)
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getSelect_CheckboxName()
   * @model
   * @generated
   */
  String getCheckboxName();

  /**
   * Sets the value of the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Select#getCheckboxName <em>Checkbox Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Checkbox Name</em>' attribute.
   * @see #getCheckboxName()
   * @generated
   */
  void setCheckboxName(String value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getSelect_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // Select
