/**
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.browserAutomationDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verify</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getTextToVerify <em>Text To Verify</em>}</li>
 *   <li>{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getLinkToVerify <em>Link To Verify</em>}</li>
 *   <li>{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getVariable <em>Variable</em>}</li>
 * </ul>
 *
 * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getVerify()
 * @model
 * @generated
 */
public interface Verify extends Command
{
  /**
   * Returns the value of the '<em><b>Text To Verify</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text To Verify</em>' attribute.
   * @see #setTextToVerify(String)
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getVerify_TextToVerify()
   * @model
   * @generated
   */
  String getTextToVerify();

  /**
   * Sets the value of the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getTextToVerify <em>Text To Verify</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text To Verify</em>' attribute.
   * @see #getTextToVerify()
   * @generated
   */
  void setTextToVerify(String value);

  /**
   * Returns the value of the '<em><b>Link To Verify</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link To Verify</em>' attribute.
   * @see #setLinkToVerify(String)
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getVerify_LinkToVerify()
   * @model
   * @generated
   */
  String getLinkToVerify();

  /**
   * Sets the value of the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getLinkToVerify <em>Link To Verify</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link To Verify</em>' attribute.
   * @see #getLinkToVerify()
   * @generated
   */
  void setLinkToVerify(String value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' attribute.
   * @see #setVariable(String)
   * @see fr.imta.yperiquoi.browserautomation.browserAutomationDSL.BrowserAutomationDSLPackage#getVerify_Variable()
   * @model
   * @generated
   */
  String getVariable();

  /**
   * Sets the value of the '{@link fr.imta.yperiquoi.browserautomation.browserAutomationDSL.Verify#getVariable <em>Variable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' attribute.
   * @see #getVariable()
   * @generated
   */
  void setVariable(String value);

} // Verify
