/*
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBrowserAutomationDSLScopeProvider extends DelegatingScopeProvider {
}
