/*
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BrowserAutomationDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/imta/yperiquoi/browserautomation/parser/antlr/internal/InternalBrowserAutomationDSL.tokens");
	}
}
