/*
 * generated by Xtext 2.32.0
 */
package fr.imta.yperiquoi.browserautomation.parser.antlr;

import com.google.inject.Inject;
import fr.imta.yperiquoi.browserautomation.parser.antlr.internal.InternalBrowserAutomationDSLParser;
import fr.imta.yperiquoi.browserautomation.services.BrowserAutomationDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BrowserAutomationDSLParser extends AbstractAntlrParser {

	@Inject
	private BrowserAutomationDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBrowserAutomationDSLParser createParser(XtextTokenStream stream) {
		return new InternalBrowserAutomationDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public BrowserAutomationDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BrowserAutomationDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
